/*
 * XMenuTest.java
 *
 * Created on November 5, 2010, 12:48 PM
 */

package test2;

/**
 *
 * @author  rameses
 */
public class XMenuTest extends javax.swing.JPanel {
    
    /** Creates new form XMenuTest */
    public XMenuTest() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xMenu1 = new com.rameses.rcp.control.XMenu();
        xContextMenu1 = new com.rameses.rcp.control.XContextMenu();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xTable1 = new com.rameses.rcp.control.XTable();
        xContextMenu2 = new com.rameses.rcp.control.XContextMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        xEditorPane1 = new com.rameses.rcp.control.XEditorPane();
        xContextMenu3 = new com.rameses.rcp.control.XContextMenu();

        xMenu1.setHandler("menuHandler");

        xContextMenu1.setHandler("menuHandler");
        xContextMenu1.setMenuFor("label");
        org.jdesktop.layout.GroupLayout xContextMenu1Layout = new org.jdesktop.layout.GroupLayout(xContextMenu1);
        xContextMenu1.setLayout(xContextMenu1Layout);
        xContextMenu1Layout.setHorizontalGroup(
            xContextMenu1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 13, Short.MAX_VALUE)
        );
        xContextMenu1Layout.setVerticalGroup(
            xContextMenu1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 14, Short.MAX_VALUE)
        );

        xLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        xLabel1.setText("Test Label");
        xLabel1.setName("label");

        xTable1.setHandler("tableHandler");
        xTable1.setName("table");

        xContextMenu2.setHandler("tblMenuHandler");
        xContextMenu2.setMenuFor("table");
        org.jdesktop.layout.GroupLayout xContextMenu2Layout = new org.jdesktop.layout.GroupLayout(xContextMenu2);
        xContextMenu2.setLayout(xContextMenu2Layout);
        xContextMenu2Layout.setHorizontalGroup(
            xContextMenu2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 14, Short.MAX_VALUE)
        );
        xContextMenu2Layout.setVerticalGroup(
            xContextMenu2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 13, Short.MAX_VALUE)
        );

        xEditorPane1.setEditable(true);
        xEditorPane1.setContentType("text/plain");
        xEditorPane1.setName("text");
        jScrollPane1.setViewportView(xEditorPane1);

        xContextMenu3.setHandler("menuHandler");
        xContextMenu3.setMenuFor("text");
        org.jdesktop.layout.GroupLayout xContextMenu3Layout = new org.jdesktop.layout.GroupLayout(xContextMenu3);
        xContextMenu3.setLayout(xContextMenu3Layout);
        xContextMenu3Layout.setHorizontalGroup(
            xContextMenu3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 13, Short.MAX_VALUE)
        );
        xContextMenu3Layout.setVerticalGroup(
            xContextMenu3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 14, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, xTable1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(xLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(xContextMenu3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                            .add(xContextMenu1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE))
                        .add(7, 7, 7))
                    .add(xMenu1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, xContextMenu2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(xMenu1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(xLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(xContextMenu1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(xContextMenu3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(xContextMenu2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(xTable1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XContextMenu xContextMenu1;
    private com.rameses.rcp.control.XContextMenu xContextMenu2;
    private com.rameses.rcp.control.XContextMenu xContextMenu3;
    private com.rameses.rcp.control.XEditorPane xEditorPane1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XMenu xMenu1;
    private com.rameses.rcp.control.XTable xTable1;
    // End of variables declaration//GEN-END:variables
    
}
