/*
 * SearchQuery.java
 *
 * Created on January 20, 2010, 11:24 AM
 */

package com.rameses.osiris2.client.templates;

/**
 *
 * @author  elmo
 */
public class LookupQueryPage extends javax.swing.JPanel {
    
    /** Creates new form SearchQuery */
    public LookupQueryPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xButton1 = new com.rameses.rcp.control.XButton();

        setLayout(null);

        setPreferredSize(new java.awt.Dimension(397, 37));
        xTextField1.setCaption("Search");
        xTextField1.setCaptionWidth(80);
        xTextField1.setName("handler.search");
        add(xTextField1);
        xTextField1.setBounds(6, 6, 336, 19);

        xButton1.setText("Search");
        xButton1.setName("handler.doSearch");
        add(xButton1);
        xButton1.setBounds(342, 5, 74, 20);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XTextField xTextField1;
    // End of variables declaration//GEN-END:variables
    
}
