package com.rameses.osiris2.client.templates;

import javax.swing.JPanel;

public class MultiLookupPage extends JPanel  {
    
    public MultiLookupPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel3 = new javax.swing.JPanel();
        xActionBar3 = new com.rameses.rcp.control.XActionBar();
        jPanel5 = new javax.swing.JPanel();
        xButton1 = new com.rameses.rcp.control.XButton();
        xButton2 = new com.rameses.rcp.control.XButton();
        xSubFormPanel1 = new com.rameses.rcp.control.XSubFormPanel();
        xTable1 = new com.rameses.rcp.control.XTable();

        setLayout(new java.awt.BorderLayout());

        setPreferredSize(new java.awt.Dimension(541, 378));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(40, 30));
        xActionBar3.setName("pageActions");
        xActionBar3.setUseToolBar(false);
        jPanel3.add(xActionBar3, java.awt.BorderLayout.CENTER);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 1, 1));

        jPanel5.setPreferredSize(new java.awt.Dimension(200, 30));
        xButton1.setText("Ok");
        xButton1.setName("select");
        jPanel5.add(xButton1);

        xButton2.setText("Cancel");
        xButton2.setImmediate(true);
        xButton2.setName("cancel");
        jPanel5.add(xButton2);

        jPanel3.add(jPanel5, java.awt.BorderLayout.EAST);

        add(jPanel3, java.awt.BorderLayout.SOUTH);

        xSubFormPanel1.setHandler("queryHandler");
        add(xSubFormPanel1, java.awt.BorderLayout.NORTH);

        xTable1.setHandler("handler");
        add(xTable1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private com.rameses.rcp.control.XActionBar xActionBar3;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XSubFormPanel xSubFormPanel1;
    private com.rameses.rcp.control.XTable xTable1;
    // End of variables declaration//GEN-END:variables
    
}
