/*
 * TestXIconPanel.java
 *
 * Created on August 26, 2010, 4:10 PM
 */

package testWindhel;

/**
 *
 * @author  rameses
 */
public class TestXIconPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form TestXIconPanel
     */
    public TestXIconPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        xImagePanel2 = new com.rameses.rcp.control.XImagePanel();
        xImagePanel1 = new com.rameses.rcp.control.XImagePanel();
        xImagePanel3 = new com.rameses.rcp.control.XImagePanel();
        xIconPanel1 = new com.rameses.rcp.control.XIconPanel();

        setLayout(new java.awt.BorderLayout());

        setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel1.setLayout(new java.awt.BorderLayout());

        xImagePanel2.setText("xImagePanel2");
        xImagePanel2.setDisplayMode("TILE");
        xImagePanel2.setName("image2");
        jPanel1.add(xImagePanel2, java.awt.BorderLayout.CENTER);

        xImagePanel1.setText("xImagePanel1");
        xImagePanel1.setName("image1");
        jPanel1.add(xImagePanel1, java.awt.BorderLayout.WEST);

        xImagePanel3.setText("xImagePanel3");
        xImagePanel3.setName("image3");
        jPanel1.add(xImagePanel3, java.awt.BorderLayout.EAST);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        xIconPanel1.setName("menuActions");
        xIconPanel1.setOrientation("CENTER");
        add(xIconPanel1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private com.rameses.rcp.control.XIconPanel xIconPanel1;
    private com.rameses.rcp.control.XImagePanel xImagePanel1;
    private com.rameses.rcp.control.XImagePanel xImagePanel2;
    private com.rameses.rcp.control.XImagePanel xImagePanel3;
    // End of variables declaration//GEN-END:variables
    
}
