/*
 * BlankPage.java
 *
 * Created on December 19, 2009, 4:59 PM
 */

package com.rameses.osiris2.netbeans;

/**
 *
 * @author  ML
 */
public class NBBlankPage extends javax.swing.JPanel {
    
    /** Creates new form BlankPage */
    public NBBlankPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
