/*
 * TestPage.java
 *
 * Created on June 19, 2010, 10:32 AM
 */

package test.client2;

/**
 *
 * @author  compaq
 */
public class TestPage extends javax.swing.JPanel {
    
    /** Creates new form TestPage */
    public TestPage() {
        initComponents();
     
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel1 = new com.rameses.rcp.util.FormPanel();

        formPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Entry"));
        formPanel1.setCaptionWidth(100);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .add(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void yButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yButton2ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_yButton2ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    // End of variables declaration//GEN-END:variables
    
}
